'''Initial migration

Revision ID: 4b377fb4be7e
Revises: 
Create Date: 2024-04-19 00:58:12.013664

'''
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b377fb4be7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('New', 'Approved', 'InProgress', 'Resolved', 'Closed', name='incidentstatus'), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.Enum('High', 'Medium', 'Low', name='incidentseverity'), nullable=False),
    sa.PrimaryKeyConstraint('incident_id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pause_time', sa.Integer(), nullable=True),
    sa.Column('time_zone', sa.Integer(), nullable=True),
    sa.Column('reg_pass', sa.String(length=255), nullable=False),
    sa.Column('last_incident_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', mysql.BIGINT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('events',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('online_sessions',
    sa.Column('user_id', mysql.BIGINT(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('scheduler_id', sa.String(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('online_sessions')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('incidents')
    # ### end Alembic commands ###
